### PR TITLE
Pedraum - Output Eslint Cyclomatic Complexity Results in JSON

### PR DESCRIPTION
**Pull request by pedraumks**
To run and store ESLint result in a JSON object:

`./node_modules/.bin/eslint --ext .js,.ts -f ./formatter.js test > eslintJsonObj.json`

eslintJsonObj.json showing cyclomatic complexity data in a JSON viewer:

Screen Shot 2019-11-18 at 1 48 47 AM

### CODE REVIEW

**Comment by danielanatolie** [comment]
@pedraumks Correct me if I am wrong, but the only way to get the json object is to run the command?

**Comment by pedraumks** [comment]
@danielanatolie yep that's correct

**Comment by jasmingoh** [comment]
@pedraumks can you spawn a child processor that runs the command? https://nodejs.org/api/child_process.html

**Comment by danielanatolie** [comment]
@jasmingoh There's no need to do that, he can just build a function runs the command, and reads the result https://github.com/danielanatolie/devis/issues/14

**Pull request merged**
